-- Oracle schema for Equipment Management System
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) DEFAULT 'user' CHECK (role IN ('user','admin'))
);

CREATE TABLE equipment (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(200) NOT NULL,
    type VARCHAR2(100),
    description VARCHAR2(500),
    total_qty NUMBER(10) DEFAULT 0,
    available_qty NUMBER(10) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE borrows (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL REFERENCES users(id),
    equipment_id NUMBER NOT NULL REFERENCES equipment(id),
    qty NUMBER(10) NOT NULL,
    status VARCHAR2(20) DEFAULT 'borrowed',
    borrowed_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    returned_at TIMESTAMP,
    feedback VARCHAR2(500)
);

CREATE INDEX idx_borrows_user ON borrows(user_id);
CREATE INDEX idx_borrows_equipment ON borrows(equipment_id);

-- Seed admin
INSERT INTO users (username, password_hash, role)
VALUES ('admin', '$2y$10$1QKAdYj6mBSJyeGrfxVlqOUInYOEoTP0TOZcdMKxF4jXIJZ99.fyW', 'admin');
-- Password is: admin123

